### ISSUE TITLE
conflict with jetpack

### ISSUE THREAD

**Issue by jackjamieson2** [dshanske/indieweb-post-kinds#235]
With Jetpack enabled, in-reply-to information is not displayed on single post pages.

e.g., here's a test post https://jackjamieson.net/2398-2/

With Jetpack enabled the single post looks like this:
![screen shot 2018-11-15 at 2 18 43 pm](https://user-images.githubusercontent.com/12275399/48576114-b19de200-e8e1-11e8-81b1-5df1029c0239.png)

And with Jetpack disabled it displays correctly:

![screen shot 2018-11-15 at 2 19 02 pm](https://user-images.githubusercontent.com/12275399/48576110-afd41e80-e8e1-11e8-90d0-59ba1473ff57.png)

Even with Jetpack enabled, the index page contains the in-reply-to markup, so this issue seems limited to single posts

This (plus the problems I had before with simple-location) have led me to disable Jetpack.  But I'm letting you know since it'd be nice to support Jetpack if possible.

**Comment by dshanske** [comment]
I fixed the location issues, by the way

**Comment by dshanske** [comment]
The module causing this is the sharing buttons one. If you disable that, ti works again.

**Comment by dshanske** [comment]
Unsure of what the conflict is.

**Comment by Cambridgeport90** [comment]
I'm not sure whether this issue is related or not, but I'm having an issue where when a kind is chosen, those fields are not enabled for the post; instead, the default ones that Wordpress supplies for standard posts (standard being the post format for standard; not sure whether or not this is a different issue?) Regardless of which kind and format is chosen. I have Jetpack enabled, but no sharing buttons, preferring to use separate plugins for that.

**Comment by veeyawn** [comment]
I'm seeing the same issue as Cambridgeport90. I start a new post as a Kind (reply, for instance) and only see the default Wordpress fields. I've completely disabled Jetpack but that did not solve the problem.

**Comment by dshanske** [comment]
@veeyawn Go under screen options and enable response properties and tell me if that helps?

**Comment by Cambridgeport90** [comment]
I can assure you, that fixed it. I’ve noticed that a lot of the response properties are the same for most of them, but that’s just a random observation.

**Comment by dshanske** [comment]
It's the same layout for everything. I had plans to customize them a bit more, but have yet to work on that. It just hides some of them if not applicable.

**Comment by veeyawn** [comment]
@dshanske checking the Response Properties in Screen Options totally fixed it. Thank you!
